name: flippy
description: A customizable split-flap Flutter widget.
version: 0.0.1
author:
homepage: https://github.com/Ilya-Korolev/flippy

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.3
